name: smoothie
description: A simple curve smoothing utility. Turn a set of your data points into a smooth Bézier curve in one line of code.
version: 0.3.0+1
homepage: https://github.com/kreitai/smoothie

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  bezier: ^1.2.0
  vector_math: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter: